packages:
  - apps/*
  - packages/*
  - frameworks/*

catalog:
  "@eslint/js": ^9.26.0
  "@next/eslint-plugin-next": ^15.3.0
  "@solidjs/meta": ^0.29.4
  "@solidjs/router": ^0.15.0
  "@solidjs/start": ^1.1.0
  "@types/node": ^20
  "@types/react": ^19
  "@types/react-dom": ^19
  astro: ^5.7.12
  eslint: ^9.26.0
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.0
  globals: ^16.0.0
  next: 15.3.2
  prettier: ^3.5.3
  react: ^19.0.0
  react-dom: ^19.0.0
  solid-js: ^1.9.5
  turbo: ^2.5.3
  typescript: ^5.8.3
  typescript-eslint: ^8.31.0
  vinxi: ^0.5.3
